### ISSUE TITLE
Some extracted images don't have names

### ISSUE THREAD

**Issue by chrismessina** [akfreas/emoji-extractor-plus#2] opened 2021-04-19 23:30 UTC
![image](https://user-images.githubusercontent.com/22610/115315597-852ec580-a12c-11eb-882b-9e3db9275d6e.png)

![image](https://user-images.githubusercontent.com/22610/115315623-911a8780-a12c-11eb-9ae4-f31b13b8e4a7.png)

Specifically, ♂ and ♀ seem to cause some problems.

**Comment by UxFFFD** [comment] 2021-04-23 08:41
Hey Chris,
how did you fix the pblist issue?

```
Requirement already satisfied: bplist==1.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.pip (line 1)) (1.1)
Requirement already satisfied: fonttools==4.22.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.pip (line 2)) (4.22.0)
Requirement already satisfied: Pillow==8.2.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from -r requirements.pip (line 3)) (8.2.0)
```

Everything seems allright, but still getting the

```
ImportError: No module named bplist.bplist
```

Searched thoroughly but found no help elsewhere...

**Comment by chrismessina** [comment] 2021-04-23 19:09
> how did you fix the pblist issue?

Did you try this?

`pip3 install bplist`

**Comment by UxFFFD** [comment] 2021-04-23 20:33
Yeah I did, but still the same error... in the meantime I have found your comment on product hunt and extracted the pngs with file juicer. The whole emoji thing is so messy – i wasn't able to rasterize https://github.com/cmdu/cmdu.github.io/blob/main/hypernormal/c0dg.png in photoshop or illustrator because the hand gets chopped off at the baseline when rasterized 🤦🏼‍♂️ Thanks for your help, I am happy to be through this 🤪

**Comment by chrismessina** [comment] 2021-04-24 00:16
> in the meantime I have found your comment on product hunt and extracted the pngs with file juicer.

File Juicer kind of makes a mess and doesn't extract at 160x160. Here's the image you wanted just in case:

![image](https://user-images.githubusercontent.com/22610/115940789-b32b4700-a457-11eb-85ce-93e353edfa75.png)

**Comment by akfreas** [comment] 2021-04-24 18:47
@cmdu Check the other issue to see if the bPlist issue is fixed with my latest commit

@chrismessina The issue with the "no name found" error comes up because there are some emojis that don't have a name in the `AppleName.strings` file in the CoreEmoji framework. They are mostly modifier emojis, used to change skin tone or hair color. I've updated the error message to show an error like this in these cases:

```
No name found for 🏾 (\U0001F3FE). This is likely a modifier emoji, it will still be saved with the filename u1F3FE.png
Try going to https://graphemica.com/🏾 to find out more.
```

The exact emoji that came up for you as not found I don't have on my system (probably cause I'm not on Big Sur), so I couldn't reproduce exactly your issue, hopefully the change helps!

**Comment by chrismessina** [comment] 2021-04-25 04:43
@akfreas nice, that helps:

```
saved ./images/160x160/white cane.png
No name found for 🦰 (\U0001F9B0). This is likely a modifier emoji, it will still be saved with the filename u1F9B0.png
Try going to https://graphemica.com/🦰 to find out more.
saved ./images/160x160/u1F9B0.png
No name found for 🦱 (\U0001F9B1). This is likely a modifier emoji, it will still be saved with the filename u1F9B1.png
Try going to https://graphemica.com/🦱 to find out more.
saved ./images/160x160/u1F9B1.png
No name found for 🦲 (\U0001F9B2). This is likely a modifier emoji, it will still be saved with the filename u1F9B2.png
Try going to https://graphemica.com/🦲 to find out more.
saved ./images/160x160/u1F9B2.png
No name found for 🦳 (\U0001F9B3). This is likely a modifier emoji, it will still be saved with the filename u1F9B3.png
Try going to https://graphemica.com/🦳 to find out more.
saved ./images/160x160/u1F9B3.png
```

Still some problems/edges cases towards the end of the extraction:

```
saved ./images/160x160/man 5.png
No name found for ♂ (). This is likely a modifier emoji, it will still be saved with the filename silhouette.MR.png
Try going to https://graphemica.com/♂ to find out more.
saved ./images/160x160/silhouette.MR.png
No name found for ♀ (). This is likely a modifier emoji, it will still be saved with the filename silhouette.WR.png
Try going to https://graphemica.com/♀ to find out more.
saved ./images/160x160/silhouette.WR.png
saved ./images/160x160/woman 2.png
No name found for  (). This is likely a modifier emoji, it will still be saved with the filename hiddenglyph.png
Try going to https://graphemica.com/ to find out more.
saved ./images/160x160/hiddenglyph.png
saved ./images/160x160/man 2.png
saved ./images/160x160/woman 3.png
saved ./images/160x160/woman 5.png
saved ./images/160x160/woman 5.png
saved ./images/160x160/woman 3.png
saved ./images/160x160/man 4.png
saved ./images/160x160/man 1.png
saved ./images/160x160/man 4.png
No name found for ♂ (). This is likely a modifier emoji, it will still be saved with the filename silhouette.ML.png
Try going to https://graphemica.com/♂ to find out more.
saved ./images/160x160/silhouette.ML.png
saved ./images/160x160/man 3.png
saved ./images/160x160/man 5.png
saved ./images/160x160/man 2.png
saved ./images/160x160/man 4.png
saved ./images/160x160/man 1.png
saved ./images/160x160/man 1.png
saved ./images/160x160/woman 2.png
saved ./images/160x160/man 3.png
No name found for ♀ (). This is likely a modifier emoji, it will still be saved with the filename silhouette.WL.png
Try going to https://graphemica.com/♀ to find out more.
saved ./images/160x160/silhouette.WL.png
```

**Comment by UxFFFD** [comment] 2021-04-26 13:07
> > in the meantime I have found your comment on product hunt and extracted the pngs with file juicer.
> 
> File Juicer kind of makes a mess and doesn't extract at 160x160. Here's the image you wanted just in case:
> 
> ![image](https://user-images.githubusercontent.com/22610/115940789-b32b4700-a457-11eb-85ce-93e353edfa75.png)

Thanks a ton for providing the png 👍🏻 @chrismessina. In my case, file juicer already gave me a 160x160 version – what confuses me about it now is that it seems to have different colors. I mean, this should have nothing to do with the extracting process. Or is there a colorprofile assign process in the extracting process 🙃

This is the file juicer Version. It is slightly more saturated.

![Apple Color Emoji-26940](https://user-images.githubusercontent.com/37655253/116087165-e1e82e00-a6a0-11eb-864d-13567aa5529a.png)

**Comment by chrismessina** [comment] 2021-04-27 04:09
> is there a colorprofile assign process in the extracting process

Hmmm, not from what I can detect, but one is 3K larger than the other!

**Closed as completed** 2021-05-03 20:50 UTC
